### ISSUE TITLE
mutiple sockets not working.

### ISSUE THREAD

**Issue by ihmpartners** [Theldus/wsServer#85]
Description
-----------
I have a small utility serving up 3 sockets on 6060, 6061 and 6062. 

I have previously compiled 3 independent files, each serving up one of the 3 sockets and this appears to work perfectly but if I combine the code into a single file and compile it, all of the responses are served up by a single message receiver.

Your environment
----------------
Both on Linux 22 and stm32embedded
    - Have you tested under the echo/echo.html example? yes/no

my C code

```
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

#include "../include/ws.h"

#include "data.h"
#include "graph.h"
#include "alerts.h"

#define MAX_PORTS   9

/**
 * @dir examples/
 * @brief wsServer examples folder
 */

/*
 * @dir examples/echo
 * @brief Echo example directory.
 * @file echo.c
 * @brief Simple echo example.
 */

/**
 * @brief Called when a client connects to the server.
 *
 * @param client Client connection. The @p client parameter is used
 * in order to send messages and retrieve informations about the
 * client.
 */
void onDataOpen(ws_cli_conn_t *client)
{
	char *cli;
	cli = ws_getaddress(client);
#ifndef DISABLE_VERBOSE
	printf("Data Connection opened, addr: %s\n", cli);
#endif
}

void onGraphOpen(ws_cli_conn_t *client)
{
	char *cli;
	cli = ws_getaddress(client);
#ifndef DISABLE_VERBOSE
	printf("Graph Connection opened, addr: %s\n", cli);
#endif
}

void onAlertsOpen(ws_cli_conn_t *client)
{
	char *cli;
	cli = ws_getaddress(client);
  #ifndef DISABLE_VERBOSE
	printf("Alerts Connection opened, addr: %s\n", cli);
  #endif
}

void onDataClose(ws_cli_conn_t *client)
{
	char *cli;
	cli = ws_getaddress(client);
#ifndef DISABLE_VERBOSE
	printf("Data Connection closed, addr: %s\n", cli);
#endif
}

void onGraphClose(ws_cli_conn_t *client)
{
	char *cli;
	cli = ws_getaddress(client);
#ifndef DISABLE_VERBOSE
	printf("Graph Connection closed, addr: %s\n", cli);
#endif
}

void onAlertsClose(ws_cli_conn_t *client)
{
	char *cli;
	cli = ws_getaddress(client);
#ifndef DISABLE_VERBOSE
	printf("Alerts Connection closed, addr: %s\n", cli);
#endif
}


void onDataMessage(ws_cli_conn_t *client,	const unsigned char *msg, uint64_t size, int type) {
	char *cli;
	cli = ws_getaddress(client);
	
  #ifndef DISABLE_VERBOSE
	printf("Received a Data message: %s (size: %" PRId64 ", type: %d), from: %s\n", msg, size, type, cli);
  #endif
	 ws_sendframe(NULL, &dvalues[0], strlen(dvalues), type);
	 }
	 

void onGraphMessage(ws_cli_conn_t *client,	const unsigned char *msg, uint64_t size, int type) {
	 char *cli;
	 cli = ws_getaddress(client);	 
	 
	 #ifndef DISABLE_VERBOSE
	 printf("Received a Graph message: %s (size: %" PRId64 ", type: %d), from: %s\n", msg, size, type, cli);
	 #endif

	 ws_sendframe(NULL, &gvalues[0], strlen(gvalues), type);
	 }
	 	 

void onAlertMessage(ws_cli_conn_t *client,	const unsigned char *msg, uint64_t size, int type) {
	 char *cli;
	 cli = ws_getaddress(client);
	 #ifndef DISABLE_VERBOSE
	 printf("Received an Alert message: %s (size: %" PRId64 ", type: %d), from: %s\n", msg, size, type, cli);
   #endif

	 ws_sendframe(NULL, &avalues[0], strlen(avalues), type);
	 }
	 

/**
 * @brief Main routine.
 *
 * @note After invoking @ref ws_socket, this routine never returns,
 * unless if invoked from a different thread.
 */
int main(void)
{

  ws_socket(&(struct ws_server){
    .host					 = "0.0.0.0",
    .port 				 = 6060,
    .thread_loop   = 1,
    .timeout_ms    = 10000,
		.evs.onopen    = &onDataOpen,
		.evs.onclose   = &onDataClose,
		.evs.onmessage = &onDataMessage
		});  
	
  ws_socket(&(struct ws_server){
    .host					 = "0.0.0.0",
    .port 				 = 6061,
    .thread_loop   = 1,
    .timeout_ms    = 10000,
 		.evs.onopen    = &onGraphOpen,
		.evs.onclose   = &onGraphClose,
		.evs.onmessage = &onGraphMessage
		});    
		
		
  ws_socket(&(struct ws_server){
    .host				 	 = "0.0.0.0",
    .port        	 = 6062,
    .thread_loop 	 = 1,
    .timeout_ms  	 = 10000,
		.evs.onopen    = &onAlertsOpen,
		.evs.onclose   = &onAlertsClose,
		.evs.onmessage = &onAlertMessage
		});		
	
	while(1){
		 int i = 0;
		 i++;
		 if (i>10000) {
		 	 i = 0;
		 }
	};

	/*
	 * If you want to execute code past ws_socket, invoke it as follows:
	 *   ws_socket(&evs, 6060, 1, 1000);
	 */

	return (0);
}
```
Three sockets are opened on 6060,6061 and 6062,

All callbacks are serviced by the AlertMessage callbacks. ( OnAlertsOpen, OnAlertsClose and onAlertMessage )

**Comment by ihmpartners** [comment]
a bit of a development ......

If the order of the ws_socket calls to create the sockets is changed then the last one in the list becomes the set that service events.

**Comment by ihmpartners** [comment]
I think I need some threads  .........

**Comment by Theldus** [comment]
Hi @ihmpartners,
This is indeed a bug that I had never noticed, thank you very much for reporting it.

Commit 2169643d7d47869098f58d372bd0fcf8ec8d1eaf should fix this. Please let me know if this works for you.

**Comment by ihmpartners** [comment]
Hi. 

Yes I am adding some more code after the socket instantiations so for the moment ...... the loop code.

I am doing some testing but currently I appear to still have a problem.

1 - Open my 3 servers 6060,6061 and 6062 and 
2 - Open the clients from a single web page. once each connection is established a simple text message is passed to the each socket which responds with a message

The following shows how the server responds. ( Chrome Web dignostics ) 

```
Subscribe to Data 6060
ws_sockets.js:23 Data Socket RECV: {"test": "D channel 6060"}
setInstGraph.js:54 Subscribe to Graph 6061
ws_sockets.js:41 Graph Socket RECV: {"test": "D channel 6060"}
ws_sockets.js:41 Graph Socket RECV: {"test": "G channel 6061"}
setInstGraph.js:60 Subscribe to Alerts 6062
ws_sockets.js:41 Graph Socket RECV: {"test": "G channel 6061"}
2ws_sockets.js:59 Alert Socket RECV: {"test": "G channel 6061"}
3ws_sockets.js:23 Data Socket RECV: {"test": "G channel 6061"}
ws_sockets.js:41 Graph Socket RECV: {"test": "G channel 6061"}
```

subscribe to .... is sent from the browser
ws_sockets.js nn is each service routine showing the data it receives. so in this case.  ( so far so good ) 
6060 opened, server on 6060 responds to 6060.
6061 opened, server on 6060 responds to 6060 and then server on 6061 responds to 6061 ( why is 6060 in here ) 
6062 opened, server on 6061 responds to 6061 6062 and then to 6060 ( some of this tranche may be from the first or second subscribe as opening 2 sockets also results in mixed messages )

**Comment by Theldus** [comment]
Hi @ihmpartners,
This is weird, I can't reproduce your issue here.... connecting to the example html (examples/echo/echo.html) on three different ports, messages are only sent and received to that port, messages are not mixed .

Could you provide me a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that shows this problem? (html + .c)

**Comment by ihmpartners** [comment]
Apache2 has the same problem so that counts that out.

**Comment by Theldus** [comment]
Hi @ihmpartners,
(Sorry for the delay; I've been quite busy in the last few days.)

Your YouTube video is set to private, and your message doesn't have any attachments. If you could look into this, I would appreciate it.

**Comment by Theldus** [comment]
@ihmpartners
Issue #86 may be related to yours and I've pushed a fix for it.
Could you check if this fix works for you too?

**Comment by ihmpartners** [comment]
Ah. I wondered about that. Will resend it all.

**Comment by Theldus** [comment]
@ihmpartners 
I've now noticed that your video is publicly available; thank you for the detailed demonstration. I finally understand what's going on.

In commit cb2c3f8 (PR #45), a code refactoring was performed, and the signature of the `ws_sendframe()` function was simplified from:

```c
int ws_sendframe(int fd, const char *msg, uint64_t size, bool broadcast, int type);
```

to:

```c
int ws_sendframe(ws_cli_conn_t *client, const char *msg, uint64_t size, int type);
```

Additionally, the broadcast functionality is now signaled when 'client' is NULL.

The issue is that, with 'client' being NULL, it becomes impossible to determine which port to send the broadcast message to. As a result, it is sent to all connected clients, regardless of their associated ports. This is why you were receiving mixed messages.

Unfortunately, this is not a bug, but at the same time, it is unexpected behavior for the user. Perhaps I should reintroduce the 'broadcast' parameter in the `ws_sendframe()/ws_sendframe_txt()/ws_sendframe_bin()` routines. What do you think? Any suggestions?

**Comment by ihmpartners** [comment]
A broadcast function would be understandable.

My requirement is that each client receives only data intended for it.

I could deal with having everything sent to all but its going to be a real
pain. A bit like having a web server that delivers every page to every
connected client.

**Comment by Theldus** [comment]
Hi @ihmpartners,
Commit fbc1547 changes the semantics of the `ws_sendframe*()` functions and introduces three new functions: `ws_sendframe_bcast()`, `ws_sendframe_txt_bcast()`, and `ws_sendframe_bin_bcast()`.

These new functions are intended for broadcasting and take the port as a parameter instead of the client, as follows:
```c
ws_sendframe_bcast(6062, msg, size, type);
ws_sendframe_txt_bcast(6062, msg);
ws_sendframe_bin_bcast(6062, msg, size);
```

The old functions still exist, but they no longer send broadcast messages, and passing a NULL client to them is now considered an error!

Please let me know if these changes works for you, and thank you very much for your persistence in helping me resolve this issue. I greatly appreciate it.

**Comment by ihmpartners** [comment]
Sorry for the delayed response but busy carving stuff out for other parts
of the project.

Working great now. individual clients, even multiple ones on the same
machine now correctly route messages only to that client!

Regards
Ian M

**Comment by Theldus** [comment]
Hi @ihmpartners,
Glad to hear it works well for you now, I'll close the issue, but feel free to open another one for any issues you have.

**Comment by ihmpartners** [comment]
Thanks.
